name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.1

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Build code
        run: |
          cd ./server
          mkdir -p ../build
          go build -o ../build/pocketbase ./cmd/app
          cp -r pb_data ../build/
          echo "${{ secrets.ENV_FILE }}" > ../build/.env

      - name: Deploy code
        run: |
          tar -czvf build.tar.gz -C ./build .
          scp -o StrictHostKeyChecking=no build.tar.gz root@${{ secrets.VM_IP_ADDR }}:/pb/build.tar.gz
          ssh -o StrictHostKeyChecking=no root@${{ secrets.VM_IP_ADDR }} "tar -xzvf /pb/build.tar.gz -C /pb"
      
      - name: Start server
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.VM_IP_ADDR }} "cd /pb && ./pocketbase serve www.dev.mybooks.tech &"
