name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.1

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

  deploy_backend:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Build code
        run: |
          cd ./server
          mkdir -p ../build
          go build -o ../build/pocketbase ./cmd/app
          cp -r pb_data ../build/
          echo "${{ secrets.ENV_FILE }}" > ../build/.env

      - name: Deploy code
        run: |
          tar -czvf build.tar.gz -C ./build .
          scp -o StrictHostKeyChecking=no build.tar.gz root@${{ secrets.VM_IP_ADDR }}:/pb/build.tar.gz
          ssh -o StrictHostKeyChecking=no root@${{ secrets.VM_IP_ADDR }} "tar -xzvf /pb/build.tar.gz -C /pb"

      - name: Start server
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.VM_IP_ADDR }} "cd /pb && ./pocketbase serve www.dev.mybooks.tech &"

  deploy_frontend:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install and build client
        run: |
          cd ./client
          npm ci
          PUBLIC_URL=https://www.dev.mybooks.tech npm run build

      - name: Deploy client
        run: |
          tar -czvf client.tar.gz -C ./client/build .
          scp -o StrictHostKeyChecking=no client.tar.gz root@${{ secrets.VM_IP_ADDR }}:/pb/client.tar.gz
          ssh -o StrictHostKeyChecking=no root@${{ secrets.VM_IP_ADDR }} "tar -xzvf /pb/client.tar.gz -C /pb/web"