name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Build code
        run: |
          cd ./server
          mkdir ../build
          go build -o ../build/pocketbase ./cmd/app
          cp -r pb_data ../build/
          

      - name: Deploy code
        run: |
          ssh root@${{ secrets.VM_IP_ADDR }} 
